# .golangci.yml

run:
    timeout: 5m
    tests: true
  
  linters:
    enable:
      - govet
      - errcheck
      - staticcheck
      - gosimple
      - unused
      - deadcode
      - typecheck
      - structcheck
      - varcheck
      - ineffassign
      - revive
      - gofmt
      - goimports
  
  linters-settings:
    gofmt:
      simplify: true
  
    revive:
      ignore-generated-header: true
      severity: warning
      rules:
        - name: indent-error-flow
          disabled: true
        - name: var-naming
          disabled: true
  
  issues:
    exclude-use-default: false
    max-same-issues: 3
    max-issues-per-linter: 0
    max-issues: 0
    exclude:
      - "should have comment or be unexported"     # often noisy for private projects
      - "field.*is unused"                          # can be noisy in WIP code
      - "error return value not checked.*(Close|Write|Flush).*\(errcheck\)"  # ignore common false positives
  
  output:
    format: colored-line-number
    sort-results: true